---
# tasks file for ansible-role-ntpd

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Download leap seconds file
  get_url:
    url: "{{ ntpd_leap_seconds_url }}"
    dest: "{{ ntpd_leapfile }}"
    force: yes

- name: Create ntpd.conf
  template:
    src: ntpd.conf.client.j2
    dest: "{{ ntpd_conf }}"
  notify: Restart ntpd
  when: "{{ ntpd_role == 'client' }}"

- name: Start ntpd
  service:
    name: "{{ ntpd_service }}"
    enabled: true
    state: started
